added update sam in yaml file

diff --git a/.github/workflows/deploysam.yaml b/.github/workflows/deploysam.yaml
--- a/.github/workflows/deploysam.yaml
+++ b/.github/workflows/deploysam.yaml
@@ -1,9 +1,10 @@
 name: Deploy Flask API using Existing Docker Image
 
 on:
-  push:
-    branches:
-      - main  # Trigger on push to the main branch
+  workflow_dispatch:  # Trigger on manual run
+  # push:
+  #   branches:
+  #     - main  # Trigger on push to the main branch
 
 jobs:
   deploy:
@@ -18,11 +19,25 @@ jobs:
       # Step 2: Install AWS SAM CLI
       - name: Install AWS SAM CLI
         run: |
-          sudo apt-get update && sudo apt-get install -y unzip
-          curl -Lo sam.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
-          unzip sam.zip -d sam-installation
-          sudo ./sam-installation/install
-          sam --version
+          if ! command -v sam &> /dev/null; then
+            echo "SAM CLI not found, installing..."
+            sudo apt-get update && sudo apt-get install -y unzip
+            curl -Lo sam.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
+            unzip sam.zip -d sam-installation
+            sudo ./sam-installation/install
+          else
+            echo "SAM CLI is already installed. Updating..."
+            sudo sam --update
+          fi
+            sam --version
+
+      # - name: Install AWS SAM CLI
+      #   run: |
+      #     sudo apt-get update && sudo apt-get install -y unzip
+      #     curl -Lo sam.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
+      #     unzip sam.zip -d sam-installation
+      #     sudo ./sam-installation/install
+      #     sam --version
 
       # Step 3: Configure AWS credentials
       - name: Configure AWS Credentials
